version: "3.8"

services:
    app:
        image: php:8.2-fpm
        container_name: focus-app-laravel
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        env_file:
            - .env-dev # Load environment variables from .env file

    web:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: laravel_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: laravel_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: nurudinismail69@gmail.com
            PGADMIN_DEFAULT_PASSWORD: mael123
        ports:
            - "5050:80"
        depends_on:
            - db

volumes:
    pgdata:
